spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: display-service
          uri: http://localhost:9000
          predicates:
            - Path=/display/**
          filters:
            - RewritePath=/display/(?<segment>.*), /$\{segment}

server:
  port: 8000
